drop database mavapt;

create database mavapt;

use mavapt;

CREATE TABLE USER
(    USERID   		 INT   	 NOT NULL AUTO_INCREMENT,
    EMAIL   		 VARCHAR(255)    NOT NULL UNIQUE,
    USERPASSWORD   	 VARCHAR(32)    NOT NULL,
    ROLE   		 VARCHAR(32),
    VALIDATED   	 TINYINT   	 NOT NULL DEFAULT 0,
PRIMARY KEY(USERID)
) ENGINE=InnoDB;

CREATE TABLE ADVISOR_SETTINGS
(    USERID   	 INT   	 NOT NULL,
    PNAME   	 VARCHAR(32)    NOT NULL,
    EMAIL   	 VARCHAR(255)    NOT NULL,
    NOTIFICATION    VARCHAR(45)    NOT NULL,
PRIMARY KEY(USERID),
FOREIGN KEY(USERID) REFERENCES USER(USERID)
) ENGINE=InnoDB;    

CREATE TABLE APPOINTMENT_TYPES
(    USERID   	 INT   	 NOT NULL,
    APT_TYPE   	 VARCHAR(45)    NOT NULL,
    DURATION    INT   	 NOT NULL,
PRIMARY KEY(USERID,APT_TYPE),
FOREIGN KEY(USERID) REFERENCES USER(USERID)
) ENGINE=InnoDB;

CREATE TABLE ADVISING_SCHEDULE
(    ID   	 INT   	 NOT NULL AUTO_INCREMENT,
    USERID   	 INT   	 NOT NULL,
    ADVISING_DATE    DATE   	 NOT NULL,
    ADVISING_STARTTIME    TIME   	 NOT NULL,
    ADVISING_ENDTIME    TIME   	 NOT NULL,
    STUDENTID    INT,
PRIMARY KEY(ID),
FOREIGN KEY(USERID) REFERENCES USER(USERID)
) ENGINE=InnoDB;

CREATE TABLE APPOINTMENTS
(    ID   	 INT   	 NOT NULL,
    ADVISOR_USERID    INT   	 NOT NULL,
    STUDENT_USERID    INT   	 NOT NULL,
    ADVISING_DATE    DATE   	 NOT NULL,
    ADVISING_STARTTIME    TIME    NOT NULL,
    ADVISING_ENDTIME    TIME    NOT NULL,
    APPOINTMENT_TYPE    VARCHAR(45)    NOT NULL,
    STUDENTID    INT   	 NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ADVISOR_USERID) REFERENCES USER(USERID),
FOREIGN KEY(STUDENT_USERID) REFERENCES USER(USERID),
FOREIGN KEY(ADVISOR_USERID,APPOINTMENT_TYPE) REFERENCES APPOINTMENT_TYPES(USERID,APT_TYPE)
) ENGINE=InnoDB;

CREATE TABLE DEPARTMENT_SETTINGS
(    ID   	 INT   	 NOT NULL,
    DEP_NAME   	 VARCHAR(45)    NOT NULL,
    ADVISING_START    TIME,
    ADVISING_END    TIME,
PRIMARY KEY(ID)
) ENGINE=InnoDB;


